services:
    app:
        image: ghcr.io/verve-tech/verve-tech:master
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.verve-tech.rule=Host(`${APP_DOMAIN:-verve-tech.localhost}`)
            - traefik.http.routers.verve-tech.entrypoints=websecure
            - traefik.http.routers.verve-tech.tls=true
            - traefik.http.routers.verve-tech.tls.certresolver=letsencrypt
            - traefik.http.services.verve-tech-service.loadbalancer.server.port=3000

networks:
    traefik:
        external: true
