<<<<<<< HEAD
import Header from '@/components/sections/Header'
=======
import Header from '@/components/layout/header'
import { cabinetGrotesk } from '@/fonts'
>>>>>>> 48369cc177c74f68a73ac161bf3a7d2a3a69a780
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Verve',
  description: 'Creative Software Agency'
}

type RootProp = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: RootProp) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
=======
    title: process.env.NEXT_PUBLIC_APP_NAME ?? 'Next.js',
    description: process.env.NEXT_PUBLIC_APP_DESCRIPTION ?? 'Generated by create next app',
    keywords: (process.env.NEXT_PUBLIC_APP_KEYWORDS ?? '').split(', ')
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${cabinetGrotesk.variable} bg-background text-foreground overflow-x-hidden font-sans antialiased`}
            >
                <Header />
                {children}
            </body>
        </html>
    )
>>>>>>> 48369cc177c74f68a73ac161bf3a7d2a3a69a780
}
