import Header from '@/components/layout/header'
import { cabinetGrotesk } from '@/fonts'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: process.env.NEXT_PUBLIC_APP_NAME ?? 'Next.js',
    description: process.env.NEXT_PUBLIC_APP_DESCRIPTION ?? 'Generated by create next app',
    keywords: (process.env.NEXT_PUBLIC_APP_KEYWORDS ?? '').split(', ')
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${cabinetGrotesk.variable} bg-background text-foreground overflow-x-hidden font-sans antialiased`}
            >
                <Header />
                {children}
            </body>
        </html>
    )
}
