name: Build and deploy application

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        name: Build and deploy
        runs-on: ubuntu-latest

        # Required for pushing to container registry
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Copy repository
              uses: actions/checkout@v4

            - name: Authenticate with container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata from Docker image
              id: docker-meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=sha

            - name: Build and push image to registry
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.docker-meta.outputs.tags }}
                  labels: ${{ steps.docker-meta.outputs.labels }}
